---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/users/alarms":
    get:
      summary: list alarms
      tags:
      - Alarms
      parameters:
      - name: params
        in: query
        schema:
          type: object
          properties:
            alarm:
              type: object
              properties:
                user_id:
                  type: integer
              required:
              - user_id
          required:
          - alarm
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                data:
                  result: true
                  total: 3
                  items:
                  - id: 431
                    slept_at: '2022-12-08T06:46:44.692Z'
                    awoke_at: '2022-12-08T14:46:44.692Z'
                    period_of_sleep: 28800
                    user_name: GOODNIGHT
                  - id: 430
                    slept_at: '2022-12-09T05:46:44.685Z'
                    awoke_at: '2022-12-09T06:46:44.685Z'
                    period_of_sleep: 3600
                    user_name: GOODNIGHT
                  - id: 429
                    slept_at: '2022-12-09T05:46:44.663Z'
                    awoke_at: '2022-12-09T06:46:44.663Z'
                    period_of_sleep: 3600
                    user_name: GOODNIGHT
        '422':
          description: params missing
  "/v1/alarms/clock_in":
    parameters:
    - name: params
      in: body
      schema:
        type: object
        properties:
          alarm:
            type: object
            properties:
              user_id:
                type: integer
              slept_at:
                type: string
                format: date-time
            required:
            - user_id
        required:
        - alarm
    post:
      summary: clock_in
      tags:
      - Alarms
      responses:
        '200':
          description: Alarm created and return list of alarm records
          content:
            application/json:
              example:
                result: true
                data:
                - id: 436
                  user_id: 491
                  slept_at: '2022-12-09T06:46:44.963Z'
                  awoke_at:
                  period_of_sleep:
                  created_at: '2022-12-09T06:46:44.969Z'
                  updated_at: '2022-12-09T06:46:44.969Z'
                - id: 435
                  user_id: 491
                  slept_at: '2022-12-08T06:46:44.955Z'
                  awoke_at: '2022-12-08T14:46:44.955Z'
                  period_of_sleep: 28800
                  created_at: '2022-12-09T06:46:44.957Z'
                  updated_at: '2022-12-09T06:46:44.960Z'
        '422':
          description: bad request
  "/v1/alarms/clock_out":
    parameters:
    - name: params
      in: body
      schema:
        type: object
        properties:
          alarm:
            type: object
            properties:
              user_id:
                type: integer
              awoke_at:
                type: string
                format: date-time
            required:
            - user_id
        required:
        - alarm
    post:
      summary: clock_out
      tags:
      - Alarms
      responses:
        '200':
          description: should update alarm record slept and return list of records
          content:
            application/json:
              example:
                result: true
                data:
                - id: 437
                  user_id: 493
                  slept_at: '2022-12-08T22:46:45.001Z'
                  awoke_at: '2022-12-09T06:46:45.005Z'
                  period_of_sleep: 28800
                  created_at: '2022-12-09T06:46:45.003Z'
                  updated_at: '2022-12-09T06:46:45.015Z'
        '422':
          description: already woke up
  "/v1/alarms/{id}":
    parameters:
    - name: id
      in: path
      description: alarm id
      required: true
      schema:
        type: integer
    - name: params
      in: body
      schema:
        type: object
        properties:
          alarm:
            type: object
            properties:
              user_id:
                type: integer
              slept_at:
                type: string
                format: date-time
              awoke_at:
                type: string
                format: date-time
            required:
            - user_id
        required:
        - alarm
    put:
      summary: update alarm
      tags:
      - Alarms
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                result: true
                data:
                  slept_at: '2022-12-08T22:46:45.038Z'
                  awoke_at: '2022-12-09T06:46:45.042Z'
                  id: 439
                  user_id: 495
                  period_of_sleep: 28800
                  created_at: '2022-12-09T06:46:45.040Z'
                  updated_at: '2022-12-09T06:46:45.049Z'
  "/v1/users/{id}/follow":
    parameters:
    - name: id
      in: path
      description: user id
      required: true
      schema:
        type: integer
    - name: params
      in: body
      schema:
        type: object
        properties:
          user:
            type: object
            properties:
              followee_id:
                type: integer
            required:
            - followee_id
        required:
        - user
    post:
      summary: follow your friend
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                result: true
                data:
                  id: 117
                  follower_id: 497
                  followee_id: 496
                  status: active
                  created_at: '2022-12-09T06:46:45.082Z'
                  updated_at: '2022-12-09T06:46:45.082Z'
        '422':
          description: already follow/ You can't follow your self
  "/v1/users/{id}/unfollow":
    parameters:
    - name: id
      in: path
      description: user id
      required: true
      schema:
        type: integer
    - name: params
      in: body
      schema:
        type: object
        properties:
          user:
            type: object
            properties:
              followee_id:
                type: integer
            required:
            - followee_id
        required:
        - user
    post:
      summary: unfollow user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                result: true
                data:
                  status: removed
                  id: 119
                  follower_id: 501
                  followee_id: 500
                  created_at: '2022-12-09T06:46:45.106Z'
                  updated_at: '2022-12-09T06:46:45.113Z'
        '422':
          description: No record exist
  "/v1/users/{id}/followee_records":
    parameters:
    - name: id
      in: path
      description: user id
      required: true
      schema:
        type: integer
    get:
      summary: followee_records user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                data:
                  result: true
                  total: 3
                  items:
                  - id: 442
                    slept_at: '2022-12-08T06:46:45.154Z'
                    awoke_at: '2022-12-08T14:46:45.154Z'
                    period_of_sleep: 28800
                    user_name: GOODNIGHT
                  - id: 440
                    slept_at: '2022-12-09T05:46:45.143Z'
                    awoke_at: '2022-12-09T06:46:45.143Z'
                    period_of_sleep: 3600
                    user_name: GOODNIGHT
                  - id: 441
                    slept_at: '2022-12-09T05:46:45.149Z'
                    awoke_at: '2022-12-09T06:46:45.149Z'
                    period_of_sleep: 3600
                    user_name: GOODNIGHT
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
